import type { ICricketer } from '@/types/interface';
import australia from '../assets/logos/australia.png';
import afghanistan from '../assets/logos/afghanistan.png';
import bangladesh from '../assets/logos/bangladesh.png';
import england from '../assets/logos/england.png';
import india from '../assets/logos/india.png';
import newZealand from '../assets/logos/new-zealand.png';
import pakistan from '../assets/logos/pakistan.png';
import southAfrica from '../assets/logos/south-africa.png';
import sriLanka from '../assets/logos/sri-lanka.png';
import westIndies from '../assets/logos/west-indies.png';

export const cricketers: ICricketer[] = [
  {
    id: 'rAp600lGb',
    name: 'Sachin Tendulkar',
    image: 'https://example.com/images/cricketers/sachin_tendulkar.jpg',
    country: 'India',
    price: 744970,
    rating: 89,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'dTr549VAy',
    name: 'Brian Lara',
    image: 'https://example.com/images/cricketers/brian_lara.jpg',
    country: 'West Indies',
    price: 745525,
    rating: 83,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'azb157Zzd',
    name: 'Shane Warne',
    image: 'https://example.com/images/cricketers/shane_warne.jpg',
    country: 'Australia',
    price: 929733,
    rating: 83,
    type: 'Bowler',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'Right-Arm-Spin',
  },
  {
    id: 'hls872dcq',
    name: 'Muttiah Muralitharan',
    image: 'https://example.com/images/cricketers/muttiah_muralitharan.jpg',
    country: 'Sri Lanka',
    price: 902605,
    rating: 98,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Left-Arm-Spin',
  },
  {
    id: 'rjZ075Ibl',
    name: 'Wasim Akram',
    image: 'https://example.com/images/cricketers/wasim_akram.jpg',
    country: 'Pakistan',
    price: 844867,
    rating: 88,
    type: 'Bowler',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'Left-Arm-Pace',
  },
  {
    id: 'pVb309EiZ',
    name: 'Ricky Ponting',
    image: 'https://example.com/images/cricketers/ricky_ponting.jpg',
    country: 'Australia',
    price: 812846,
    rating: 87,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'ArL402ULP',
    name: 'Jacques Kallis',
    image: 'https://example.com/images/cricketers/jacques_kallis.jpg',
    country: 'South Africa',
    price: 592778,
    rating: 80,
    type: 'All-Rounder',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'HTi385Dep',
    name: 'MS Dhoni',
    image: 'https://example.com/images/cricketers/ms_dhoni.jpg',
    country: 'India',
    price: 778716,
    rating: 91,
    type: 'Wicket-Keeper',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'SQM085Tpi',
    name: 'Virender Sehwag',
    image: 'https://example.com/images/cricketers/virender_sehwag.jpg',
    country: 'India',
    price: 683853,
    rating: 99,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'qdx487Hsw',
    name: 'Kumar Sangakkara',
    image: 'https://example.com/images/cricketers/kumar_sangakkara.jpg',
    country: 'Sri Lanka',
    price: 917256,
    rating: 82,
    type: 'Wicket-Keeper',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'aBO869CWh',
    name: 'Sachin Tendulkar',
    image: 'https://example.com/images/cricketers/sachin_tendulkar.jpg',
    country: 'India',
    price: 646902,
    rating: 81,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'rkF007tOd',
    name: 'Brian Lara',
    image: 'https://example.com/images/cricketers/brian_lara.jpg',
    country: 'West Indies',
    price: 540826,
    rating: 95,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'dwH132bXq',
    name: 'Shane Warne',
    image: 'https://example.com/images/cricketers/shane_warne.jpg',
    country: 'Australia',
    price: 621576,
    rating: 99,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Left-Arm-Spin',
  },
  {
    id: 'Kzz781IXI',
    name: 'Muttiah Muralitharan',
    image: 'https://example.com/images/cricketers/muttiah_muralitharan.jpg',
    country: 'Sri Lanka',
    price: 941404,
    rating: 80,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'zUi918pes',
    name: 'Wasim Akram',
    image: 'https://example.com/images/cricketers/wasim_akram.jpg',
    country: 'Pakistan',
    price: 513741,
    rating: 80,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Left-Arm-Spin',
  },
  {
    id: 'Yuq845XJH',
    name: 'Ricky Ponting',
    image: 'https://example.com/images/cricketers/ricky_ponting.jpg',
    country: 'Australia',
    price: 770256,
    rating: 94,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'cip778vao',
    name: 'Jacques Kallis',
    image: 'https://example.com/images/cricketers/jacques_kallis.jpg',
    country: 'South Africa',
    price: 910431,
    rating: 86,
    type: 'All-Rounder',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'Right-Arm-Spin',
  },
  {
    id: 'OQf191hII',
    name: 'MS Dhoni',
    image: 'https://example.com/images/cricketers/ms_dhoni.jpg',
    country: 'India',
    price: 791872,
    rating: 83,
    type: 'Wicket-Keeper',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'Left-Arm-Spin',
  },
  {
    id: 'osN831TYS',
    name: 'Virender Sehwag',
    image: 'https://example.com/images/cricketers/virender_sehwag.jpg',
    country: 'India',
    price: 616065,
    rating: 84,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'jig807evX',
    name: 'Kumar Sangakkara',
    image: 'https://example.com/images/cricketers/kumar_sangakkara.jpg',
    country: 'Sri Lanka',
    price: 866248,
    rating: 89,
    type: 'Wicket-Keeper',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Left-Arm-Spin',
  },
  {
    id: 'Twt520Kod',
    name: 'Sachin Tendulkar',
    image: 'https://example.com/images/cricketers/sachin_tendulkar.jpg',
    country: 'India',
    price: 599144,
    rating: 100,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'LpW612qgI',
    name: 'Brian Lara',
    image: 'https://example.com/images/cricketers/brian_lara.jpg',
    country: 'West Indies',
    price: 926098,
    rating: 85,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'Vza731bEp',
    name: 'Shane Warne',
    image: 'https://example.com/images/cricketers/shane_warne.jpg',
    country: 'Australia',
    price: 561150,
    rating: 82,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Left-Arm-Pace',
  },
  {
    id: 'jZe545sPr',
    name: 'Muttiah Muralitharan',
    image: 'https://example.com/images/cricketers/muttiah_muralitharan.jpg',
    country: 'Sri Lanka',
    price: 646222,
    rating: 90,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Left-Arm-Spin',
  },
  {
    id: 'ACe100KJX',
    name: 'Wasim Akram',
    image: 'https://example.com/images/cricketers/wasim_akram.jpg',
    country: 'Pakistan',
    price: 518059,
    rating: 89,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Left-Arm-Pace',
  },
  {
    id: 'dhD508DlS',
    name: 'Ricky Ponting',
    image: 'https://example.com/images/cricketers/ricky_ponting.jpg',
    country: 'Australia',
    price: 696320,
    rating: 91,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'iXY268GRq',
    name: 'Jacques Kallis',
    image: 'https://example.com/images/cricketers/jacques_kallis.jpg',
    country: 'South Africa',
    price: 735632,
    rating: 80,
    type: 'All-Rounder',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'oxv943dQZ',
    name: 'MS Dhoni',
    image: 'https://example.com/images/cricketers/ms_dhoni.jpg',
    country: 'India',
    price: 756081,
    rating: 82,
    type: 'Wicket-Keeper',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Left-Arm-Pace',
  },
  {
    id: 'DXC621zNQ',
    name: 'Virender Sehwag',
    image: 'https://example.com/images/cricketers/virender_sehwag.jpg',
    country: 'India',
    price: 721134,
    rating: 100,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'aSt758HVr',
    name: 'Kumar Sangakkara',
    image: 'https://example.com/images/cricketers/kumar_sangakkara.jpg',
    country: 'Sri Lanka',
    price: 941295,
    rating: 85,
    type: 'Wicket-Keeper',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'gJy182oss',
    name: 'Sachin Tendulkar',
    image: 'https://example.com/images/cricketers/sachin_tendulkar.jpg',
    country: 'India',
    price: 802909,
    rating: 81,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'xYQ460sFq',
    name: 'Brian Lara',
    image: 'https://example.com/images/cricketers/brian_lara.jpg',
    country: 'West Indies',
    price: 897677,
    rating: 85,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'seV428rUC',
    name: 'Shane Warne',
    image: 'https://example.com/images/cricketers/shane_warne.jpg',
    country: 'Australia',
    price: 604619,
    rating: 86,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Left-Arm-Spin',
  },
  {
    id: 'ZfG779koU',
    name: 'Muttiah Muralitharan',
    image: 'https://example.com/images/cricketers/muttiah_muralitharan.jpg',
    country: 'Sri Lanka',
    price: 657401,
    rating: 93,
    type: 'Bowler',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'Right-Arm-Spin',
  },
  {
    id: 'PAz312GnI',
    name: 'Wasim Akram',
    image: 'https://example.com/images/cricketers/wasim_akram.jpg',
    country: 'Pakistan',
    price: 529367,
    rating: 99,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'Yiz599DBw',
    name: 'Ricky Ponting',
    image: 'https://example.com/images/cricketers/ricky_ponting.jpg',
    country: 'Australia',
    price: 853025,
    rating: 98,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'XIJ344kXr',
    name: 'Jacques Kallis',
    image: 'https://example.com/images/cricketers/jacques_kallis.jpg',
    country: 'South Africa',
    price: 549194,
    rating: 88,
    type: 'All-Rounder',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'geD686Pxg',
    name: 'MS Dhoni',
    image: 'https://example.com/images/cricketers/ms_dhoni.jpg',
    country: 'India',
    price: 506890,
    rating: 91,
    type: 'Wicket-Keeper',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'xVo620gfn',
    name: 'Virender Sehwag',
    image: 'https://example.com/images/cricketers/virender_sehwag.jpg',
    country: 'India',
    price: 598675,
    rating: 93,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'Zow324utR',
    name: 'Kumar Sangakkara',
    image: 'https://example.com/images/cricketers/kumar_sangakkara.jpg',
    country: 'Sri Lanka',
    price: 731257,
    rating: 100,
    type: 'Wicket-Keeper',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'Left-Arm-Spin',
  },
  {
    id: 'rfV833UWy',
    name: 'Sachin Tendulkar',
    image: 'https://example.com/images/cricketers/sachin_tendulkar.jpg',
    country: 'India',
    price: 738800,
    rating: 81,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'yeK873DIe',
    name: 'Brian Lara',
    image: 'https://example.com/images/cricketers/brian_lara.jpg',
    country: 'West Indies',
    price: 764127,
    rating: 90,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'mGP017feB',
    name: 'Shane Warne',
    image: 'https://example.com/images/cricketers/shane_warne.jpg',
    country: 'Australia',
    price: 608316,
    rating: 86,
    type: 'Bowler',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'bBL799ACm',
    name: 'Muttiah Muralitharan',
    image: 'https://example.com/images/cricketers/muttiah_muralitharan.jpg',
    country: 'Sri Lanka',
    price: 884413,
    rating: 90,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'EcI021ADm',
    name: 'Wasim Akram',
    image: 'https://example.com/images/cricketers/wasim_akram.jpg',
    country: 'Pakistan',
    price: 619190,
    rating: 87,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Left-Arm-Spin',
  },
  {
    id: 'lSE585Kvo',
    name: 'Ricky Ponting',
    image: 'https://example.com/images/cricketers/ricky_ponting.jpg',
    country: 'Australia',
    price: 726038,
    rating: 91,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'QZz081NlE',
    name: 'Jacques Kallis',
    image: 'https://example.com/images/cricketers/jacques_kallis.jpg',
    country: 'South Africa',
    price: 826811,
    rating: 90,
    type: 'All-Rounder',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'DAx786DYt',
    name: 'MS Dhoni',
    image: 'https://example.com/images/cricketers/ms_dhoni.jpg',
    country: 'India',
    price: 817573,
    rating: 84,
    type: 'Wicket-Keeper',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Left-Arm-Pace',
  },
  {
    id: 'LGn633kvZ',
    name: 'Virender Sehwag',
    image: 'https://example.com/images/cricketers/virender_sehwag.jpg',
    country: 'India',
    price: 911286,
    rating: 82,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'qyG805vzU',
    name: 'Kumar Sangakkara',
    image: 'https://example.com/images/cricketers/kumar_sangakkara.jpg',
    country: 'Sri Lanka',
    price: 532024,
    rating: 93,
    type: 'Wicket-Keeper',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Left-Arm-Spin',
  },
];

export const logos: Record<string, string> = {
  Australia: australia,
  Bangladesh: bangladesh,
  Afghanistan: afghanistan,
  Pakistan: pakistan,
  England: england,
  India: india,
  'New Zealand': newZealand,
  'South Africa': southAfrica,
  'West Indies': westIndies,
  'Sri Lanka': sriLanka,
};
