import type { ICricketer } from '@/types/interface';
import australia from '../assets/logos/australia.png';
import afghanistan from '../assets/logos/afghanistan.png';
import bangladesh from '../assets/logos/bangladesh.png';
import england from '../assets/logos/england.png';
import india from '../assets/logos/india.png';
import newZealand from '../assets/logos/new-zealand.png';
import pakistan from '../assets/logos/pakistan.png';
import southAfrica from '../assets/logos/south-africa.png';
import sriLanka from '../assets/logos/sri-lanka.png';
import westIndies from '../assets/logos/west-indies.png';

export const cricketers: ICricketer[] = [
  {
    id: 'nz104wkt',
    name: 'Brendon McCullum',
    image:
      'https://upload.wikimedia.org/wikipedia/en/3/3f/Brendon_McCullum_2015.jpg',
    country: 'New Zealand',
    price: 600000,
    rating: 90,
    type: 'Wicket-Keeper',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'nz107bat',
    name: 'Nathan Astle',
    image: 'https://upload.wikimedia.org/wikipedia/en/6/63/Nathan_Astle.jpg',
    country: 'New Zealand',
    price: 480000,
    rating: 82,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'nz108all',
    name: 'Daniel Vettori',
    image: 'https://upload.wikimedia.org/wikipedia/en/5/5f/Daniel_Vettori.jpg',
    country: 'New Zealand',
    price: 500000,
    rating: 87,
    type: 'All-Rounder',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Left-Arm-Spin',
  },
  {
    id: 'nz109all',
    name: 'Daniel Vettori',
    image: 'https://upload.wikimedia.org/wikipedia/en/1/1e/Sam_Smith.png',
    country: 'New Zealand',
    price: 420000,
    rating: 80,
    type: 'All-Rounder',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'nz110bwl',
    name: 'Kyle Jamieson',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/d/d0/Kyle_Jamieson_2020.jpg',
    country: 'New Zealand',
    price: 530000,
    rating: 84,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'nz111bwl',
    name: 'Lockie Ferguson',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/7/76/Lockie_Ferguson_2019.jpg',
    country: 'New Zealand',
    price: 560000,
    rating: 85,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'nz112bwl',
    name: 'Will Somerville',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/e/e0/Will_Somerville_2016.jpg',
    country: 'New Zealand',
    price: 470000,
    rating: 78,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Spin',
  },
  {
    id: 'nz113wkt',
    name: 'Tom Latham',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/d/d3/Tom_Latham_2017.jpg',
    country: 'New Zealand',
    price: 590000,
    rating: 88,
    type: 'Wicket-Keeper',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'nz114bat',
    name: 'Mark Richardson',
    image: 'https://upload.wikimedia.org/wikipedia/en/1/15/Mark_Richardson.jpg',
    country: 'New Zealand',
    price: 460000,
    rating: 81,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'nz115all',
    name: 'Jacob Oram',
    image: 'https://upload.wikimedia.org/wikipedia/en/b/b9/Ross_Taylor.jpg',
    country: 'New Zealand',
    price: 550000,
    rating: 89,
    type: 'All-Rounder',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'ind100bat',
    name: 'Sachin Tendulkar',
    image: 'https://example.com/images/sachin_tendulkar.jpg',
    country: 'India',
    price: 500000,
    rating: 98,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'wi100bat',
    name: 'Brian Lara',
    image: 'https://example.com/images/brian_lara.jpg',
    country: 'West Indies',
    price: 450000,
    rating: 96,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'aus100bwl',
    name: 'Shane Warne',
    image: 'https://example.com/images/shane_warne.jpg',
    country: 'Australia',
    price: 400000,
    rating: 95,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Spin',
  },
  {
    id: 'sl100bwl',
    name: 'Muttiah Muralitharan',
    image: 'https://example.com/images/muttiah_muralitharan.jpg',
    country: 'Sri Lanka',
    price: 450000,
    rating: 97,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Spin',
  },
  {
    id: 'pak100bwl',
    name: 'Wasim Akram',
    image: 'https://example.com/images/wasim_akram.jpg',
    country: 'Pakistan',
    price: 500000,
    rating: 94,
    type: 'Bowler',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'Left-Arm-Pace',
  },
  {
    id: 'aus101bat',
    name: 'Ricky Ponting',
    image: 'https://example.com/images/ricky_ponting.jpg',
    country: 'Australia',
    price: 475000,
    rating: 95,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'sa100all',
    name: 'Jacques Kallis',
    image: 'https://example.com/images/jacques_kallis.jpg',
    country: 'South Africa',
    price: 525000,
    rating: 97,
    type: 'All-Rounder',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'ind101wkt',
    name: 'MS Dhoni',
    image: 'https://example.com/images/ms_dhoni.jpg',
    country: 'India',
    price: 470000,
    rating: 95,
    type: 'Wicket-Keeper',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'ind102bat',
    name: 'Virender Sehwag',
    image: 'https://example.com/images/virender_sehwag.jpg',
    country: 'India',
    price: 460000,
    rating: 93,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'sl101wkt',
    name: 'Kumar Sangakkara',
    image: 'https://example.com/images/kumar_sangakkara.jpg',
    country: 'Sri Lanka',
    price: 460000,
    rating: 94,
    type: 'Wicket-Keeper',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'ind103bat',
    name: 'Rahul Dravid',
    image: 'https://example.com/images/rahul_dravid.jpg',
    country: 'India',
    price: 450000,
    rating: 93,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'aus102bat',
    name: 'Adam Gilchrist',
    image: 'https://example.com/images/adam_gilchrist.jpg',
    country: 'Australia',
    price: 440000,
    rating: 92,
    type: 'Wicket-Keeper',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'wi101all',
    name: 'Chris Gayle',
    image: 'https://example.com/images/chris_gayle.jpg',
    country: 'West Indies',
    price: 450000,
    rating: 91,
    type: 'All-Rounder',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'Right-Arm-Spin',
  },
  {
    id: 'sa101bat',
    name: 'AB de-Villiers',
    image: 'https://example.com/images/ab_de_villiers.jpg',
    country: 'South Africa',
    price: 460000,
    rating: 95,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'aus103bat',
    name: 'Michael Clarke',
    image: 'https://example.com/images/michael_clarke.jpg',
    country: 'Australia',
    price: 430000,
    rating: 90,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'ind104bat',
    name: 'Sourav Ganguly',
    image: 'https://example.com/images/sourav_ganguly.jpg',
    country: 'India',
    price: 420000,
    rating: 91,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'nz105bat',
    name: 'Glen Turner',
    image: 'https://upload.wikimedia.org/wikipedia/en/0/0c/Glen_Turner.jpg',
    country: 'New Zealand',
    price: 450000,
    rating: 85,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'aus104bwl',
    name: 'Glenn McGrath',
    image: 'https://example.com/images/glenn_mcgrath.jpg',
    country: 'Australia',
    price: 460000,
    rating: 93,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'ind105all',
    name: 'Yuvraj Singh',
    image: 'https://example.com/images/yuvraj_singh.jpg',
    country: 'India',
    price: 450000,
    rating: 92,
    type: 'All-Rounder',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'Left-Arm-Spin',
  },
  {
    id: 'pak101bat',
    name: 'Inzamam-ul Haq',
    image: 'https://example.com/images/inzamam_ul_haq.jpg',
    country: 'Pakistan',
    price: 420000,
    rating: 91,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'nz100bat',
    name: 'Stephen Fleming',
    image: 'https://example.com/images/stephen_fleming.jpg',
    country: 'New Zealand',
    price: 410000,
    rating: 90,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'pak102bwl',
    name: 'Shoaib Akhtar',
    image: 'https://example.com/images/shoaib_akhtar.jpg',
    country: 'Pakistan',
    price: 400000,
    rating: 92,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'sl102all',
    name: 'Sanath Jayasuriya',
    image: 'https://example.com/images/sanath_jayasuriya.jpg',
    country: 'Sri Lanka',
    price: 420000,
    rating: 90,
    type: 'All-Rounder',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'Left-Arm-Spin',
  },
  {
    id: 'sl103bat',
    name: 'Mahela Jayawardene',
    image: 'https://example.com/images/mahela_jayawardene.jpg',
    country: 'Sri Lanka',
    price: 410000,
    rating: 89,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'aus105bwl',
    name: 'Brett Lee',
    image: 'https://example.com/images/brett_lee.jpg',
    country: 'Australia',
    price: 440000,
    rating: 92,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'eng100bat',
    name: 'Kevin Pietersen',
    image: 'https://example.com/images/kevin_pietersen.jpg',
    country: 'England',
    price: 430000,
    rating: 90,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'ind106bat',
    name: 'VVS Laxman',
    image: 'https://example.com/images/vvs_laxman.jpg',
    country: 'India',
    price: 410000,
    rating: 89,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'wi102all',
    name: 'Andre Russell',
    image: 'https://example.com/images/andre_russell.jpg',
    country: 'West Indies',
    price: 460000,
    rating: 91,
    type: 'All-Rounder',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'nz101bat',
    name: 'Kane Williamson',
    image: 'https://example.com/images/kane_williamson.jpg',
    country: 'New Zealand',
    price: 490000,
    rating: 94,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'aus106bat',
    name: 'Steve Smith',
    image: 'https://example.com/images/steve_smith.jpg',
    country: 'Australia',
    price: 470000,
    rating: 94,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'wi103bwl',
    name: 'Courtney Walsh',
    image: 'https://example.com/images/courtney_walsh.jpg',
    country: 'West Indies',
    price: 430000,
    rating: 89,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'eng101all',
    name: 'Ben Stokes',
    image: 'https://example.com/images/ben_stokes.jpg',
    country: 'England',
    price: 520000,
    rating: 95,
    type: 'All-Rounder',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'sa102bat',
    name: 'Hashim Amla',
    image: 'https://example.com/images/hashim_amla.jpg',
    country: 'South Africa',
    price: 410000,
    rating: 90,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'pak103bat',
    name: 'Mohammad Yousuf',
    image: 'https://example.com/images/mohammad_yousuf.jpg',
    country: 'Pakistan',
    price: 410000,
    rating: 89,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'nz102bat',
    name: 'Ross Taylor',
    image: 'https://example.com/images/ross_taylor.jpg',
    country: 'New Zealand',
    price: 400000,
    rating: 89,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'ind107bat',
    name: 'Rohit Sharma',
    image: 'https://example.com/images/rohit_sharma.jpg',
    country: 'India',
    price: 490000,
    rating: 94,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'aus107all',
    name: 'Mitchell Marsh',
    image: 'https://example.com/images/mitchell_marsh.jpg',
    country: 'Australia',
    price: 450000,
    rating: 89,
    type: 'All-Rounder',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'wi104bwl',
    name: 'Joel Garner',
    image: 'https://example.com/images/joel_garner.jpg',
    country: 'West Indies',
    price: 430000,
    rating: 91,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'eng102wkt',
    name: 'Jos Buttler',
    image: 'https://example.com/images/jos_buttler.jpg',
    country: 'England',
    price: 470000,
    rating: 93,
    type: 'Wicket-Keeper',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'ind108bat',
    name: 'Shikhar Dhawan',
    image: 'https://example.com/images/shikhar_dhawan.jpg',
    country: 'India',
    price: 460000,
    rating: 90,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'aus108bat',
    name: 'David Warner',
    image: 'https://example.com/images/david_warner.jpg',
    country: 'Australia',
    price: 490000,
    rating: 92,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'ind109all',
    name: 'Hardik Pandya',
    image: 'https://example.com/images/hardik_pandya.jpg',
    country: 'India',
    price: 450000,
    rating: 88,
    type: 'All-Rounder',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'nz103bwl',
    name: 'Trent Boult',
    image: 'https://example.com/images/trent_boult.jpg',
    country: 'New Zealand',
    price: 460000,
    rating: 90,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Left-Arm-Pace',
  },
  {
    id: 'ind110bwl',
    name: 'Jasprit Bumrah',
    image: 'https://example.com/images/jasprit_bumrah.jpg',
    country: 'India',
    price: 480000,
    rating: 93,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'nz106bat',
    name: 'Martin Guptill',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/d/d2/Martin_Guptill_2015.jpg',
    country: 'New Zealand',
    price: 550000,
    rating: 88,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'aus109wkt',
    name: 'Matthew Wade',
    image: 'https://example.com/images/matthew_wade.jpg',
    country: 'Australia',
    price: 410000,
    rating: 89,
    type: 'Wicket-Keeper',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'wi105all',
    name: 'Dwayne Bravo',
    image: 'https://example.com/images/dwayne_bravo.jpg',
    country: 'West Indies',
    price: 430000,
    rating: 91,
    type: 'All-Rounder',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'eng103bat',
    name: 'Alastair Cook',
    image: 'https://example.com/images/alastair_cook.jpg',
    country: 'England',
    price: 430000,
    rating: 89,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'sa103bwl',
    name: 'Dale Steyn',
    image: 'https://example.com/images/dale_steyn.jpg',
    country: 'South Africa',
    price: 450000,
    rating: 93,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'ind111bat',
    name: 'KL Rahul',
    image: 'https://example.com/images/kl_rahul.jpg',
    country: 'India',
    price: 470000,
    rating: 92,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'sa104all',
    name: 'Chris Morris',
    image: 'https://example.com/images/chris_morris.jpg',
    country: 'South Africa',
    price: 440000,
    rating: 88,
    type: 'All-Rounder',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'pak104wkt',
    name: 'Kamran Akmal',
    image: 'https://example.com/images/kamran_akmal.jpg',
    country: 'Pakistan',
    price: 400000,
    rating: 85,
    type: 'Wicket-Keeper',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'ban201bat',
    name: 'Tamim Iqbal',
    image: 'https://example.com/images/tamim_iqbal.jpg',
    country: 'Bangladesh',
    price: 380000,
    rating: 88,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'ban202all',
    name: 'Shakib Al-Hasan',
    image: 'https://example.com/images/shakib_al_hasan.jpg',
    country: 'Bangladesh',
    price: 450000,
    rating: 93,
    type: 'All-Rounder',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'Left-Arm-Spin',
  },
  {
    id: 'ban203bat',
    name: 'Mushfiqur Rahim',
    image: 'https://example.com/images/mushfiqur_rahim.jpg',
    country: 'Bangladesh',
    price: 400000,
    rating: 87,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'ban204bwl',
    name: 'Mustafizur Rahman',
    image: 'https://example.com/images/mustafizur_rahman.jpg',
    country: 'Bangladesh',
    price: 420000,
    rating: 86,
    type: 'Bowler',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'Left-Arm-Pace',
  },
  {
    id: 'ban205bwl',
    name: 'Taskin Ahmed',
    image: 'https://example.com/images/taskin_ahmed.jpg',
    country: 'Bangladesh',
    price: 410000,
    rating: 84,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'ban206all',
    name: 'Mahmudullah',
    image: 'https://example.com/images/mahmudullah.jpg',
    country: 'Bangladesh',
    price: 370000,
    rating: 82,
    type: 'All-Rounder',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Spin',
  },
  {
    id: 'ban207wkt',
    name: 'Liton Das',
    image: 'https://example.com/images/liton_das.jpg',
    country: 'Bangladesh',
    price: 390000,
    rating: 83,
    type: 'Wicket-Keeper',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'ban208bat',
    name: 'Soumya Sarkar',
    image: 'https://example.com/images/soumya_sarkar.jpg',
    country: 'Bangladesh',
    price: 360000,
    rating: 80,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'afg201all',
    name: 'Mohammad Nabi',
    image: 'https://example.com/images/mohammad_nabi.jpg',
    country: 'Afghanistan',
    price: 410000,
    rating: 88,
    type: 'All-Rounder',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Spin',
  },
  {
    id: 'afg202bat',
    name: 'Hazratullah Zazai',
    image: 'https://example.com/images/hazratullah_zazai.jpg',
    country: 'Afghanistan',
    price: 390000,
    rating: 82,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'afg203bwl',
    name: 'Rashid Khan',
    image: 'https://example.com/images/rashid_khan.jpg',
    country: 'Afghanistan',
    price: 450000,
    rating: 93,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Spin',
  },
  {
    id: 'afg204bat',
    name: 'Asghar Afghan',
    image: 'https://example.com/images/asghar_afghan.jpg',
    country: 'Afghanistan',
    price: 360000,
    rating: 81,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'afg205all',
    name: 'Gulbadin Naib',
    image: 'https://example.com/images/gulbadin_naib.jpg',
    country: 'Afghanistan',
    price: 370000,
    rating: 82,
    type: 'All-Rounder',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'afg206wkt',
    name: 'Mohammad Shahzad',
    image: 'https://example.com/images/mohammad_shahzad.jpg',
    country: 'Afghanistan',
    price: 380000,
    rating: 83,
    type: 'Wicket-Keeper',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'afg207bat',
    name: 'Rahmat Shah',
    image: 'https://example.com/images/rahmat_shah.jpg',
    country: 'Afghanistan',
    price: 360000,
    rating: 80,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'afg208bwl',
    name: 'Mujeeb-ur Rahman',
    image: 'https://example.com/images/mujeeb_ur_rahman.jpg',
    country: 'Afghanistan',
    price: 410000,
    rating: 87,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Spin',
  },
  {
    id: 'ban209bat',
    name: 'Imrul Kayes',
    image: 'https://example.com/images/imrul_kayes.jpg',
    country: 'Bangladesh',
    price: 350000,
    rating: 79,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'ban210bwl',
    name: 'Rubel Hossain',
    image: 'https://example.com/images/rubel_hossain.jpg',
    country: 'Bangladesh',
    price: 400000,
    rating: 83,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'afg209all',
    name: 'Karim Janat',
    image: 'https://example.com/images/karim_janat.jpg',
    country: 'Afghanistan',
    price: 380000,
    rating: 82,
    type: 'All-Rounder',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'afg210bat',
    name: 'Hashmatullah Shahidi',
    image: 'https://example.com/images/hashmatullah_shahidi.jpg',
    country: 'Afghanistan',
    price: 370000,
    rating: 81,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'pak105bat',
    name: 'Babar Azam',
    image: 'https://example.com/images/babar_azam.jpg',
    country: 'Pakistan',
    price: 500000,
    rating: 94,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'pak106all',
    name: 'Shadab Khan',
    image: 'https://example.com/images/shadab_khan.jpg',
    country: 'Pakistan',
    price: 450000,
    rating: 87,
    type: 'All-Rounder',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Spin',
  },
  {
    id: 'pak107wkt',
    name: 'Mohammad Rizwan',
    image: 'https://example.com/images/mohammad_rizwan.jpg',
    country: 'Pakistan',
    price: 480000,
    rating: 91,
    type: 'Wicket-Keeper',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'pak108bwl',
    name: 'Shaheen Afridi',
    image: 'https://example.com/images/shaheen_afridi.jpg',
    country: 'Pakistan',
    price: 470000,
    rating: 89,
    type: 'Bowler',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'Left-Arm-Pace',
  },
  {
    id: 'pak109bat',
    name: 'Fakhar Zaman',
    image: 'https://example.com/images/fakhar_zaman.jpg',
    country: 'Pakistan',
    price: 370000,
    rating: 84,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'pak110all',
    name: 'Imad Wasim',
    image: 'https://example.com/images/imad_wasim.jpg',
    country: 'Pakistan',
    price: 390000,
    rating: 85,
    type: 'All-Rounder',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'Left-Arm-Spin',
  },
  {
    id: 'pak111bwl',
    name: 'Hasan Ali',
    image: 'https://example.com/images/hasan_ali.jpg',
    country: 'Pakistan',
    price: 380000,
    rating: 83,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'pak112bat',
    name: 'Shoaib Malik',
    image: 'https://example.com/images/shoaib_malik.jpg',
    country: 'Pakistan',
    price: 370000,
    rating: 82,
    type: 'All-Rounder',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Spin',
  },
  {
    id: 'pak113wkt',
    name: 'Sarfaraz Ahmed',
    image: 'https://example.com/images/sarfaraz_ahmed.jpg',
    country: 'Pakistan',
    price: 350000,
    rating: 80,
    type: 'Wicket-Keeper',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'pak114bwl',
    name: 'Wahab Riaz',
    image: 'https://example.com/images/wahab_riaz.jpg',
    country: 'Pakistan',
    price: 370000,
    rating: 81,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Left-Arm-Pace',
  },
  {
    id: 'pak115bat',
    name: 'Asif Ali',
    image: 'https://example.com/images/asif_ali.jpg',
    country: 'Pakistan',
    price: 320000,
    rating: 77,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'pak116bwl',
    name: 'Mohammad Hasnain',
    image: 'https://example.com/images/mohammad_hasnain.jpg',
    country: 'Pakistan',
    price: 340000,
    rating: 79,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'pak117bat',
    name: 'Haider Ali',
    image: 'https://example.com/images/haider_ali.jpg',
    country: 'Pakistan',
    price: 310000,
    rating: 76,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'pak118all',
    name: 'Mohammad Nawaz',
    image: 'https://example.com/images/mohammad_nawaz.jpg',
    country: 'Pakistan',
    price: 360000,
    rating: 80,
    type: 'All-Rounder',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'Left-Arm-Spin',
  },
  {
    id: 'pak119bwl',
    name: 'Yasir Shah',
    image: 'https://example.com/images/yasir_shah.jpg',
    country: 'Pakistan',
    price: 350000,
    rating: 78,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Spin',
  },
  {
    id: 'pak120all',
    name: 'Faheem Ashraf',
    image: 'https://example.com/images/faheem_ashraf.jpg',
    country: 'Pakistan',
    price: 340000,
    rating: 78,
    type: 'All-Rounder',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'pak121bat',
    name: 'Imam-ul-Haq',
    image: 'https://example.com/images/imam_ul_haq.jpg',
    country: 'Pakistan',
    price: 380000,
    rating: 82,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'pak122bwl',
    name: 'Mohammad Asif',
    image: 'https://example.com/images/kamran_akmal.jpg',
    country: 'Pakistan',
    price: 330000,
    rating: 76,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
];

export const logos: Record<string, string> = {
  Australia: australia,
  Bangladesh: bangladesh,
  Afghanistan: afghanistan,
  Pakistan: pakistan,
  England: england,
  India: india,
  'New Zealand': newZealand,
  'South Africa': southAfrica,
  'West Indies': westIndies,
  'Sri Lanka': sriLanka,
};
