import type { ICricketer } from '@/types/interface';
import australia from '../assets/logos/australia.png';
import afghanistan from '../assets/logos/afghanistan.png';
import bangladesh from '../assets/logos/bangladesh.png';
import england from '../assets/logos/england.png';
import india from '../assets/logos/india.png';
import newZealand from '../assets/logos/new-zealand.png';
import pakistan from '../assets/logos/pakistan.png';
import southAfrica from '../assets/logos/south-africa.png';
import sriLanka from '../assets/logos/sri-lanka.png';
import westIndies from '../assets/logos/west-indies.png';
import allRounder from '../assets/cricketers/all-round.jpg';
import astle from '../assets/cricketers/astle.jpg';
import batsman from '../assets/cricketers/batsman.jpg';
import bowler from '../assets/cricketers/bowler.jpg';
import ferguson from '../assets/cricketers/ferguson.jpg';
import graemeSmith from '../assets/cricketers/graeme-smith.jpeg';
import jamieson from '../assets/cricketers/jamieson.jpg';
import keeper from '../assets/cricketers/keeper.png';
import lara from '../assets/cricketers/lara.jpg';
import latham from '../assets/cricketers/latham.jpg';
import McCullum from '../assets/cricketers/McCullum.jpg';
import muralitharan from '../assets/cricketers/muralitharan.jpg';
import oram from '../assets/cricketers/oram.jpg';
import richardson from '../assets/cricketers/richardson.jpg';
import shaneWarne from '../assets/cricketers/shane-warne.jpg';
import somerville from '../assets/cricketers/somerville.jpg';
import tendulkar from '../assets/cricketers/tendulkar.jpg';
import vettori from '../assets/cricketers/vettori.jpg';

export const cricketers: ICricketer[] = [
  {
    id: 'nz104wkt',
    name: 'Brendon McCullum',
    image: McCullum,
    country: 'New Zealand',
    price: 600000,
    rating: 90,
    type: 'Wicket-Keeper',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'nz107bat',
    name: 'Nathan Astle',
    image: astle,
    country: 'New Zealand',
    price: 480000,
    rating: 82,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'nz108all',
    name: 'Daniel Vettori',
    image: vettori,
    country: 'New Zealand',
    price: 500000,
    rating: 87,
    type: 'All-Rounder',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Left-Arm-Spin',
  },
  {
    id: 'sa106bat',
    name: 'Graeme Smith',
    image: graemeSmith,
    country: 'South Africa',
    price: 420000,
    rating: 80,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'nz110bwl',
    name: 'Kyle Jamieson',
    image: jamieson,
    country: 'New Zealand',
    price: 530000,
    rating: 84,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'nz111bwl',
    name: 'Lockie Ferguson',
    image: ferguson,
    country: 'New Zealand',
    price: 560000,
    rating: 85,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'nz112bwl',
    name: 'Will Somerville',
    image: somerville,
    country: 'New Zealand',
    price: 470000,
    rating: 78,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Spin',
  },
  {
    id: 'nz113wkt',
    name: 'Tom Latham',
    image: latham,
    country: 'New Zealand',
    price: 590000,
    rating: 88,
    type: 'Wicket-Keeper',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'nz114bat',
    name: 'Mark Richardson',
    image: richardson,
    country: 'New Zealand',
    price: 460000,
    rating: 81,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'nz115all',
    name: 'Jacob Oram',
    image: oram,
    country: 'New Zealand',
    price: 550000,
    rating: 89,
    type: 'All-Rounder',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'ind100bat',
    name: 'Sachin Tendulkar',
    image: tendulkar,
    country: 'India',
    price: 500000,
    rating: 98,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'wi100bat',
    name: 'Brian Lara',
    image: lara,
    country: 'West Indies',
    price: 450000,
    rating: 96,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'aus100bwl',
    name: 'Shane Warne',
    image: shaneWarne,
    country: 'Australia',
    price: 400000,
    rating: 95,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Spin',
  },
  {
    id: 'sl100bwl',
    name: 'Muttiah Muralitharan',
    image: muralitharan,
    country: 'Sri Lanka',
    price: 450000,
    rating: 97,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Spin',
  },
  {
    id: 'pak100bwl',
    name: 'Wasim Akram',
    image: bowler,
    country: 'Pakistan',
    price: 500000,
    rating: 94,
    type: 'Bowler',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'Left-Arm-Pace',
  },
  {
    id: 'aus101bat',
    name: 'Ricky Ponting',
    image: batsman,
    country: 'Australia',
    price: 475000,
    rating: 95,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'sa100all',
    name: 'Jacques Kallis',
    image: allRounder,
    country: 'South Africa',
    price: 525000,
    rating: 97,
    type: 'All-Rounder',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'ind101wkt',
    name: 'MS Dhoni',
    image: keeper,
    country: 'India',
    price: 470000,
    rating: 95,
    type: 'Wicket-Keeper',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'ind102bat',
    name: 'Virender Sehwag',
    image: batsman,
    country: 'India',
    price: 460000,
    rating: 93,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'sl101wkt',
    name: 'Kumar Sangakkara',
    image: keeper,
    country: 'Sri Lanka',
    price: 460000,
    rating: 94,
    type: 'Wicket-Keeper',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'ind103bat',
    name: 'Rahul Dravid',
    image: batsman,
    country: 'India',
    price: 450000,
    rating: 93,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'aus102bat',
    name: 'Adam Gilchrist',
    image: keeper,
    country: 'Australia',
    price: 440000,
    rating: 92,
    type: 'Wicket-Keeper',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'wi101all',
    name: 'Chris Gayle',
    image: allRounder,
    country: 'West Indies',
    price: 450000,
    rating: 91,
    type: 'All-Rounder',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'Right-Arm-Spin',
  },
  {
    id: 'sa101bat',
    name: 'AB de-Villiers',
    image: batsman,
    country: 'South Africa',
    price: 460000,
    rating: 95,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'aus103bat',
    name: 'Michael Clarke',
    image: batsman,
    country: 'Australia',
    price: 430000,
    rating: 90,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'ind104bat',
    name: 'Sourav Ganguly',
    image: batsman,
    country: 'India',
    price: 420000,
    rating: 91,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'nz105bat',
    name: 'Glen Turner',
    image: batsman,
    country: 'New Zealand',
    price: 450000,
    rating: 85,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'aus104bwl',
    name: 'Glenn McGrath',
    image: bowler,
    country: 'Australia',
    price: 460000,
    rating: 93,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'ind105all',
    name: 'Yuvraj Singh',
    image: allRounder,
    country: 'India',
    price: 450000,
    rating: 92,
    type: 'All-Rounder',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'Left-Arm-Spin',
  },
  {
    id: 'pak101bat',
    name: 'Inzamam-ul Haq',
    image: batsman,
    country: 'Pakistan',
    price: 420000,
    rating: 91,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'nz100bat',
    name: 'Stephen Fleming',
    image: batsman,
    country: 'New Zealand',
    price: 410000,
    rating: 90,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'pak102bwl',
    name: 'Shoaib Akhtar',
    image: bowler,
    country: 'Pakistan',
    price: 400000,
    rating: 92,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'sl102all',
    name: 'Sanath Jayasuriya',
    image: allRounder,
    country: 'Sri Lanka',
    price: 420000,
    rating: 90,
    type: 'All-Rounder',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'Left-Arm-Spin',
  },
  {
    id: 'sl103bat',
    name: 'Mahela Jayawardene',
    image: batsman,
    country: 'Sri Lanka',
    price: 410000,
    rating: 89,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'aus105bwl',
    name: 'Brett Lee',
    image: bowler,
    country: 'Australia',
    price: 440000,
    rating: 92,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'eng100bat',
    name: 'Kevin Pietersen',
    image: batsman,
    country: 'England',
    price: 430000,
    rating: 90,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'ind106bat',
    name: 'VVS Laxman',
    image: batsman,
    country: 'India',
    price: 410000,
    rating: 89,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'wi102all',
    name: 'Andre Russell',
    image: allRounder,
    country: 'West Indies',
    price: 460000,
    rating: 91,
    type: 'All-Rounder',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'nz101bat',
    name: 'Kane Williamson',
    image: batsman,
    country: 'New Zealand',
    price: 490000,
    rating: 94,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'aus106bat',
    name: 'Steve Smith',
    image: batsman,
    country: 'Australia',
    price: 470000,
    rating: 94,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'wi103bwl',
    name: 'Courtney Walsh',
    image: bowler,
    country: 'West Indies',
    price: 430000,
    rating: 89,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'eng101all',
    name: 'Ben Stokes',
    image: allRounder,
    country: 'England',
    price: 520000,
    rating: 95,
    type: 'All-Rounder',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'sa102bat',
    name: 'Hashim Amla',
    image: batsman,
    country: 'South Africa',
    price: 410000,
    rating: 90,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'pak103bat',
    name: 'Mohammad Yousuf',
    image: batsman,
    country: 'Pakistan',
    price: 410000,
    rating: 89,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'nz102bat',
    name: 'Ross Taylor',
    image: batsman,
    country: 'New Zealand',
    price: 400000,
    rating: 89,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'ind107bat',
    name: 'Rohit Sharma',
    image: batsman,
    country: 'India',
    price: 490000,
    rating: 94,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'aus107all',
    name: 'Mitchell Marsh',
    image: allRounder,
    country: 'Australia',
    price: 450000,
    rating: 89,
    type: 'All-Rounder',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'wi104bwl',
    name: 'Joel Garner',
    image: bowler,
    country: 'West Indies',
    price: 430000,
    rating: 91,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'eng102wkt',
    name: 'Jos Buttler',
    image: keeper,
    country: 'England',
    price: 470000,
    rating: 93,
    type: 'Wicket-Keeper',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'ind108bat',
    name: 'Shikhar Dhawan',
    image: batsman,
    country: 'India',
    price: 460000,
    rating: 90,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'aus108bat',
    name: 'David Warner',
    image: batsman,
    country: 'Australia',
    price: 490000,
    rating: 92,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'ind109all',
    name: 'Hardik Pandya',
    image: allRounder,
    country: 'India',
    price: 450000,
    rating: 88,
    type: 'All-Rounder',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'nz103bwl',
    name: 'Trent Boult',
    image: bowler,
    country: 'New Zealand',
    price: 460000,
    rating: 90,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Left-Arm-Pace',
  },
  {
    id: 'ind110bwl',
    name: 'Jasprit Bumrah',
    image: bowler,
    country: 'India',
    price: 480000,
    rating: 93,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'nz106bat',
    name: 'Martin Guptill',
    image: batsman,
    country: 'New Zealand',
    price: 550000,
    rating: 88,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'aus109wkt',
    name: 'Matthew Wade',
    image: keeper,
    country: 'Australia',
    price: 410000,
    rating: 89,
    type: 'Wicket-Keeper',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'wi105all',
    name: 'Dwayne Bravo',
    image: allRounder,
    country: 'West Indies',
    price: 430000,
    rating: 91,
    type: 'All-Rounder',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'eng103bat',
    name: 'Alastair Cook',
    image: batsman,
    country: 'England',
    price: 430000,
    rating: 89,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'sa103bwl',
    name: 'Dale Steyn',
    image: bowler,
    country: 'South Africa',
    price: 450000,
    rating: 93,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'ind111bat',
    name: 'KL Rahul',
    image: batsman,
    country: 'India',
    price: 470000,
    rating: 92,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'sa104all',
    name: 'Chris Morris',
    image: allRounder,
    country: 'South Africa',
    price: 440000,
    rating: 88,
    type: 'All-Rounder',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'pak104wkt',
    name: 'Kamran Akmal',
    image: keeper,
    country: 'Pakistan',
    price: 400000,
    rating: 85,
    type: 'Wicket-Keeper',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'ban201bat',
    name: 'Tamim Iqbal',
    image: batsman,
    country: 'Bangladesh',
    price: 380000,
    rating: 88,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'ban202all',
    name: 'Shakib Al-Hasan',
    image: allRounder,
    country: 'Bangladesh',
    price: 450000,
    rating: 93,
    type: 'All-Rounder',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'Left-Arm-Spin',
  },
  {
    id: 'ban203bat',
    name: 'Mushfiqur Rahim',
    image: batsman,
    country: 'Bangladesh',
    price: 400000,
    rating: 87,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'ban204bwl',
    name: 'Mustafizur Rahman',
    image: bowler,
    country: 'Bangladesh',
    price: 420000,
    rating: 86,
    type: 'Bowler',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'Left-Arm-Pace',
  },
  {
    id: 'ban205bwl',
    name: 'Taskin Ahmed',
    image: bowler,
    country: 'Bangladesh',
    price: 410000,
    rating: 84,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'ban206all',
    name: 'Mahmudullah',
    image: allRounder,
    country: 'Bangladesh',
    price: 370000,
    rating: 82,
    type: 'All-Rounder',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Spin',
  },
  {
    id: 'ban207wkt',
    name: 'Liton Das',
    image: keeper,
    country: 'Bangladesh',
    price: 390000,
    rating: 83,
    type: 'Wicket-Keeper',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'ban208bat',
    name: 'Soumya Sarkar',
    image: batsman,
    country: 'Bangladesh',
    price: 360000,
    rating: 80,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'afg201all',
    name: 'Mohammad Nabi',
    image: allRounder,
    country: 'Afghanistan',
    price: 410000,
    rating: 88,
    type: 'All-Rounder',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Spin',
  },
  {
    id: 'afg202bat',
    name: 'Hazratullah Zazai',
    image: batsman,
    country: 'Afghanistan',
    price: 390000,
    rating: 82,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'afg203bwl',
    name: 'Rashid Khan',
    image: bowler,
    country: 'Afghanistan',
    price: 450000,
    rating: 93,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Spin',
  },
  {
    id: 'afg204bat',
    name: 'Asghar Afghan',
    image: batsman,
    country: 'Afghanistan',
    price: 360000,
    rating: 81,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'afg205all',
    name: 'Gulbadin Naib',
    image: allRounder,
    country: 'Afghanistan',
    price: 370000,
    rating: 82,
    type: 'All-Rounder',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'afg206wkt',
    name: 'Mohammad Shahzad',
    image: keeper,
    country: 'Afghanistan',
    price: 380000,
    rating: 83,
    type: 'Wicket-Keeper',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'afg207bat',
    name: 'Rahmat Shah',
    image: batsman,
    country: 'Afghanistan',
    price: 360000,
    rating: 80,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'afg208bwl',
    name: 'Mujeeb-ur Rahman',
    image: bowler,
    country: 'Afghanistan',
    price: 410000,
    rating: 87,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Spin',
  },
  {
    id: 'ban209bat',
    name: 'Imrul Kayes',
    image: batsman,
    country: 'Bangladesh',
    price: 350000,
    rating: 79,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'ban210bwl',
    name: 'Rubel Hossain',
    image: bowler,
    country: 'Bangladesh',
    price: 400000,
    rating: 83,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'afg209all',
    name: 'Karim Janat',
    image: allRounder,
    country: 'Afghanistan',
    price: 380000,
    rating: 82,
    type: 'All-Rounder',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'afg210bat',
    name: 'Hashmatullah Shahidi',
    image: batsman,
    country: 'Afghanistan',
    price: 370000,
    rating: 81,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'pak105bat',
    name: 'Babar Azam',
    image: batsman,
    country: 'Pakistan',
    price: 500000,
    rating: 94,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'pak106all',
    name: 'Shadab Khan',
    image: allRounder,
    country: 'Pakistan',
    price: 450000,
    rating: 87,
    type: 'All-Rounder',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Spin',
  },
  {
    id: 'pak107wkt',
    name: 'Mohammad Rizwan',
    image: keeper,
    country: 'Pakistan',
    price: 480000,
    rating: 91,
    type: 'Wicket-Keeper',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'pak108bwl',
    name: 'Shaheen Afridi',
    image: bowler,
    country: 'Pakistan',
    price: 470000,
    rating: 89,
    type: 'Bowler',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'Left-Arm-Pace',
  },
  {
    id: 'pak109bat',
    name: 'Fakhar Zaman',
    image: batsman,
    country: 'Pakistan',
    price: 370000,
    rating: 84,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'pak110all',
    name: 'Imad Wasim',
    image: allRounder,
    country: 'Pakistan',
    price: 390000,
    rating: 85,
    type: 'All-Rounder',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'Left-Arm-Spin',
  },
  {
    id: 'pak111bwl',
    name: 'Hasan Ali',
    image: bowler,
    country: 'Pakistan',
    price: 380000,
    rating: 83,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'pak112bat',
    name: 'Shoaib Malik',
    image: allRounder,
    country: 'Pakistan',
    price: 370000,
    rating: 82,
    type: 'All-Rounder',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Spin',
  },
  {
    id: 'pak113wkt',
    name: 'Sarfaraz Ahmed',
    image: keeper,
    country: 'Pakistan',
    price: 350000,
    rating: 80,
    type: 'Wicket-Keeper',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'pak114bwl',
    name: 'Wahab Riaz',
    image: bowler,
    country: 'Pakistan',
    price: 370000,
    rating: 81,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Left-Arm-Pace',
  },
  {
    id: 'pak115bat',
    name: 'Asif Ali',
    image: batsman,
    country: 'Pakistan',
    price: 320000,
    rating: 77,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'pak116bwl',
    name: 'Mohammad Hasnain',
    image: bowler,
    country: 'Pakistan',
    price: 340000,
    rating: 79,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'pak117bat',
    name: 'Haider Ali',
    image: batsman,
    country: 'Pakistan',
    price: 310000,
    rating: 76,
    type: 'Batsman',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'pak118all',
    name: 'Mohammad Nawaz',
    image: allRounder,
    country: 'Pakistan',
    price: 360000,
    rating: 80,
    type: 'All-Rounder',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'Left-Arm-Spin',
  },
  {
    id: 'pak119bwl',
    name: 'Yasir Shah',
    image: bowler,
    country: 'Pakistan',
    price: 350000,
    rating: 78,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Spin',
  },
  {
    id: 'pak120all',
    name: 'Faheem Ashraf',
    image: allRounder,
    country: 'Pakistan',
    price: 340000,
    rating: 78,
    type: 'All-Rounder',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
  {
    id: 'pak121bat',
    name: 'Imam-ul-Haq',
    image: batsman,
    country: 'Pakistan',
    price: 380000,
    rating: 82,
    type: 'Batsman',
    battingStyle: 'Left-Hand-Bat',
    bowlingStyle: 'None',
  },
  {
    id: 'pak122bwl',
    name: 'Mohammad Asif',
    image: bowler,
    country: 'Pakistan',
    price: 330000,
    rating: 76,
    type: 'Bowler',
    battingStyle: 'Right-Hand-Bat',
    bowlingStyle: 'Right-Arm-Pace',
  },
];

export const logos: Record<string, string> = {
  Australia: australia,
  Bangladesh: bangladesh,
  Afghanistan: afghanistan,
  Pakistan: pakistan,
  England: england,
  India: india,
  'New Zealand': newZealand,
  'South Africa': southAfrica,
  'West Indies': westIndies,
  'Sri Lanka': sriLanka,
};
